#!/usr/bin/env python

# core
import argparse
import logging
import os
import sys

# local
from cathpy import util

parser = argparse.ArgumentParser(
    description="Provide summary stats for alignments")

parser.add_argument('--in', type=str, dest='dir_in', required=True,
    help='alignment directory')

parser.add_argument('--suffix', type=str, dest='suffix', default='.sto', 
    help='suffix to use when matching alignment files')

parser.add_argument('--skipempty', default=False, action="store_true",
    help='skip empty files')

parser.add_argument('--verbose', '-v', required=False, action='count', default=0,
    help='more verbose logging')

if __name__ == '__main__':
    args = parser.parse_args()

    log_level = logging.DEBUG if args.verbose > 0 else logging.INFO
    logging.basicConfig(level=log_level)

    aln_sum = util.AlignmentSummaryRunner(dir_in=args.dir_in, suffix=args.suffix, 
        skipempty=args.skipempty)

    aln_sum.run()

    logging.info('DONE')
